"""add_status_to_train_movements

Revision ID: 3411d90eb9e9
Revises: 22bc8f5fa09c
Create Date: 2026-09-18 18:00:31.770758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3411d90eb9e9'
down_revision: Union[str, Sequence[str], None] = '22bc8f5fa09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train_movements_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train_movements_history', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
